In [10]:
#                                STATISTICS AND NUMPY

# Importing numpy library.
import numpy as np
# Now we will use 'np' instead of 'numpy'.


# QUESTION 1:
# Create a numpy array with 10 elements of the shape(10, 1) using np.random and
# find out the mean of the elements using basic numpy functions.

my_array = np.random.rand(10, 1)
print("Numpy array with 10 elements of the shape(10, 1):\n", my_array)
print("\nMean of the numpy array elements: ", np.mean(my_array))

Numpy array with 10 elements of the shape(10, 1):
 [[0.03750898]
 [0.28892756]
 [0.19020039]
 [0.44513544]
 [0.72711666]
 [0.51940635]
 [0.27577305]
 [0.75016421]
 [0.19342972]
 [0.4999894 ]]

Mean of the numpy array elements:  0.3927651778413564


In [11]:
# QUESTION 2:
# Create a numpy array with 20 elements of the shape(20, 1) using np.random and
# find the variance and standard deviation of the elements.

my_array1 = np.random.rand(20, 1)
print("Numpy array with 20 elements of the shape(20, 1):\n", my_array1)

# Calculating the standard deviation using numpy library function(np.std(array)).
print("\nStandard deviation of elements in array: ", np.std(my_array1))
# Calculating the variance using numpy library function(np.var(array)).
print("Variance of elements in array: ", np.var(my_array1))

Numpy array with 20 elements of the shape(20, 1):
 [[0.24857207]
 [0.77516017]
 [0.88266897]
 [0.41846409]
 [0.93538885]
 [0.98957198]
 [0.73654328]
 [0.63129531]
 [0.61666803]
 [0.51018724]
 [0.2103235 ]
 [0.19838173]
 [0.97922422]
 [0.63714746]
 [0.40518036]
 [0.53971601]
 [0.3177069 ]
 [0.34794509]
 [0.17274372]
 [0.53252846]]

Standard deviation of elements in array:  0.25958452220235884
Variance of elements in array:  0.06738412416702692


In [9]:
# QUESTION 3:
# Create a numpy array A of shape(10, 20) and B of shape (20, 25) using np.random.
# Print the matrix which is the matrix multiplication of A and B.
# The shape of the new matrix should be (10, 25).
# Using basic numpy math functions only
# find the sum of all the elements of the new matrix.

array_A = np.random.rand(10, 20)
print("Numpy array A of shape(10, 20):\n", array_A)
array_B = np.random.rand(20, 25)
print("\nNumpy array B of shape(20, 25):\n", array_B)

# Calculating the matrix multiplication using numpy library function(np.dot(a, b)).
matrix_multiplication = np.dot(array_A, array_B)
print("\nMatrix multiplication of array A and array B:\n", matrix_multiplication)

print("\nSum of all the elements of the new matrix: ", np.sum(matrix_multiplication))

Numpy array A of shape(10, 20):
 [[0.28675992 0.09794651 0.32296423 0.733717   0.23103033 0.12576577
  0.63744884 0.99866849 0.19723781 0.01937721 0.18298668 0.12040722
  0.6474558  0.95506127 0.31402672 0.56256091 0.94936914 0.82199243
  0.19424769 0.94768816]
 [0.19131824 0.70465628 0.44137327 0.45789255 0.67194257 0.63072425
  0.3398298  0.62331841 0.09145971 0.77803019 0.8159393  0.42573761
  0.93069449 0.07164395 0.66769268 0.39850458 0.71795545 0.97880247
  0.1179983  0.29545485]
 [0.76128544 0.55700406 0.23398504 0.3674924  0.57146728 0.07648411
  0.94795302 0.22482802 0.23954974 0.42823209 0.15999175 0.21869914
  0.93265083 0.89087191 0.85530746 0.91299593 0.98331459 0.44420208
  0.8734338  0.94383433]
 [0.47434561 0.23222766 0.31771348 0.3507183  0.98442363 0.15988653
  0.5043133  0.99285435 0.75292675 0.63653029 0.91015177 0.7944876
  0.48694701 0.06181691 0.16365323 0.50777847 0.55002642 0.24536914
  0.66841509 0.07033708]
 [0.31023301 0.73390376 0.00978089 0.459678   0.1206

In [8]:
# QUESTION 4:
# Create a numpy array A of shape(10, 1).
# Using the basic operations of the numpy array generate an array of shape(10, 1)
# such that each element is the following function applied on each element of A.
#       f(x) = 1 / (1 + exp(-x))
# Apply this function to each element of A and print the new array holding the value the function returns
# Example:
#       a = [a1, a2, a3]
#       n(new array to be printed ) = [ f(a1), f(a2), f(a3)]

array_A1 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print("Numpy array A of shape(10, 1):\n", array_A1)


def function1(x):
    return 1 / (1 + np.exp(-x))


new_array = function1(array_A1)
print("\nAfter applying function to each element of array A, the new array to be printed:\n", new_array)

Numpy array A of shape(10, 1):
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

After applying function to each element of array A, the new array to be printed:
 [[0.73105858]
 [0.88079708]
 [0.95257413]
 [0.98201379]
 [0.99330715]
 [0.99752738]
 [0.99908895]
 [0.99966465]
 [0.99987661]
 [0.9999546 ]]


In [7]:
# Finally done

print("Done")

Done
