# PCA (Principal Component Analysis)

In [ ]:
# In this assignment, you are going to perform PCA on MNIST analysis.


# Q.1- Import MNIST dataset from sklearn. Save data and targets in variables X and Y respectively.

# Q.2- Perform feature scaling. 
#      (http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler)

# Q.3- Split data into training and testing sets.

# Q.4- Perform PCA. Take any value for components.

# Q.5- Perform classification (logistic regression).

# Q.6- Print the following: 
#   a. Accuracy score
#   b. Confusion Matrix
#   c. Classification Report

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits # Importing mnist dataset from sklearn.
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#### Question 1:

In [3]:
digit = load_digits()
print(digit.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [4]:
# Data is stored in x whereas target is in y variable
x = digit.data
print(x)
y = digit.target
print(y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


#### Question 2:

In [5]:
# Feature scaling using StandardScaler
x_std = StandardScaler().fit_transform(x) 
print(x_std)

[[ 0.         -0.33501649 -0.04308102 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  0.54856067 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  1.56568555  1.6951369
  -0.19600752]
 ...
 [ 0.         -0.33501649 -0.88456568 ... -0.12952258 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.67419451 ...  0.8876023  -0.5056698
  -0.19600752]
 [ 0.         -0.33501649  1.00877481 ...  0.8876023  -0.26113572
  -0.19600752]]


#### Question 3:

In [6]:
# Spliting data into training and testing set
x_train, x_test, y_train, y_test = train_test_split(x_std, y, test_size=0.4, random_state=20)

#### Question 4:

In [7]:
pca = PCA(n_components=0.96 )

# Fiting the training part in 
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

#### Question 5:

In [8]:
# Classification usng logistic regression model
log = LogisticRegression()

# Fiting the training part into model
log.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [9]:
# Prediction over model
prediction = log.predict(x_test)

#### Question 6:

In [10]:
# Accuracy score
accuracy_score(y_test, prediction)

0.9541029207232267

In [12]:
# Confusion Matrix
print(confusion_matrix(y_test, prediction))

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 72  0  1  0  0  0  0  1  1]
 [ 0  0 63  0  0  0  0  0  0  0]
 [ 0  0  0 73  0  3  0  1  3  0]
 [ 0  1  0  0 72  0  0  1  0  1]
 [ 1  0  0  0  0 70  0  0  0  0]
 [ 0  0  0  0  2  0 69  0  0  0]
 [ 0  0  0  1  0  0  0 78  0  1]
 [ 0  2  0  0  0  1  1  1 58  1]
 [ 0  1  0  0  0  1  0  1  6 68]]


In [14]:
# Classification report
print(classification_report(y_test, prediction, labels=None, digits=3))

             precision    recall  f1-score   support

          0      0.984     1.000     0.992        63
          1      0.947     0.960     0.954        75
          2      1.000     1.000     1.000        63
          3      0.973     0.912     0.942        80
          4      0.973     0.960     0.966        75
          5      0.933     0.986     0.959        71
          6      0.986     0.972     0.979        71
          7      0.951     0.975     0.963        80
          8      0.853     0.906     0.879        64
          9      0.944     0.883     0.913        77

avg / total      0.955     0.954     0.954       719

