# Naive Baiyes Algorithm

In [5]:
# Q.1- What is the probability of a person playing when the weather is sunny? Find P(Yes|Sunny).

#   Weather 	Play
#   Sunny	No
#   Overcast	Yes
#   Rainy	Yes
#   Sunny	Yes
#   Sunny	Yes
#   Overcast	Yes
#   Rainy	No
#   Rainy	No
#   Sunny	Yes
#   Rainy	Yes
#   Sunny	No
#   Overcast	Yes
#   Overcast	Yes
#   Rainy	No


# Q.2- Solve the following:
#      a) Import iris dataset from sklearn.

#      b) Split the dataset into training and testing sets using train_test_split() 

#      c) Use GaussianNB and print the following:
#         i. Confusion matrix
#         ii. Classification report

#      d) Use MultinomialNB and print the following:
#         i. Confusion matrix
#         ii. Classification report

#### Question 1:

P(yes/sunny) = p(sunny/yes) * p(yes) / p(sunny)
Answer - 3/5

#### Question 2:

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [19]:
iris = datasets.load_iris()
x = iris.data
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=20)

gnb = GaussianNB()
print(gnb.fit(x_train, y_train))

GaussianNB(priors=None)


In [14]:
g_pred = gnb.predict(x_test)
print(classification_report(y_test, g_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        24
          1       0.89      1.00      0.94        33
          2       1.00      0.78      0.88        18

avg / total       0.95      0.95      0.94        75



In [15]:
print(confusion_matrix(y_test, g_pred))

[[24  0  0]
 [ 0 33  0]
 [ 0  4 14]]


In [20]:
mnb = MultinomialNB()
print(mnb.fit(x_train, y_train))

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [22]:
m_pred = mnb.predict(x_test)
print(classification_report(y_test, m_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        24
          1       0.00      0.00      0.00        33
          2       0.35      1.00      0.52        18

avg / total       0.40      0.56      0.45        75



C:\Users\intel\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [24]:
print(confusion_matrix( y_test, m_pred))

[[24  0  0]
 [ 0  0 33]
 [ 0  0 18]]
